### ISSUE TITLE
On linux with VB, calico fails to set cni confile

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/sig-windows-dev-tools#111]
I tried the set up on Linux and got:

```
winw1: All set ! your calico cluster should be up shortly !
    winw1: DONE INSTALLING CALICO I THINK !
    winw1: 
    winw1: DisplayHint : DateTime
    winw1: Date        : 9/29/2021 12:00:00 AM
    winw1: Day         : 29
    winw1: DayOfWeek   : Wednesday
    winw1: DayOfYear   : 272
    winw1: Hour        : 10
    winw1: Kind        : Local
    winw1: Millisecond : 120
    winw1: Minute      : 23
    winw1: Month       : 9
    winw1: Second      : 31
    winw1: Ticks       : 637685078111205978
    winw1: TimeOfDay   : 10:23:31.1205978
    winw1: Year        : 2021
    winw1: DateTime    : Wednesday, September 29, 2021 10:23:31 AM
    winw1: 
    winw1: 
    winw1: Status      : Running
    winw1: Name        : CalicoNode
    winw1: DisplayName : Calico Windows Startup
    winw1: 
    winw1: 
    winw1: Status      : Running
    winw1: Name        : CalicoFelix
    winw1: DisplayName : Calico Windows Agent
    winw1: 
    winw1: 
    winw1: 
    winw1: Set-Content : Stream was not readable.
    winw1: At C:\CalicoWindows\libs\calico\calico.psm1:141 char:9
    winw1: +     } | Set-Content "$cniConfFile"
    winw1: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    winw1:     + CategoryInfo          : InvalidArgument: (C:\etc\cni\net.d\10-calico.conf:String) [Set-Content], ArgumentExcepti
    winw1:    on
    winw1:     + FullyQualifiedErrorId : GetContentWriterArgumentError,Microsoft.PowerShell.Commands.SetContentCommand
    winw1: 
touch cni
```

looks close but cni isn't ready:

```
vagrant ssh controlplane
cni:
calico
Last login: Wed Sep 29 17:18:01 2021 from 10.0.2.2
vagrant@controlplane:~$ kubectl get nodes
NAME           STATUS     ROLES                  AGE   VERSION
controlplane   Ready      control-plane,master   77m   v1.21.0
winw1          NotReady   <none>                 13m   v1.21.2-rc.0
```

**Comment by jsturtevant** [comment]
running `vagrant provision winw1` a second time worked but the node is still not "ready":

```
 winw1: Service "kube-proxy" installed successfully!
    winw1: Set parameter "AppParameters" for service "kube-proxy".
    winw1: Set parameter "AppDirectory" for service "kube-proxy".
    winw1: 
    winw1: Set parameter "Description" for service "kube-proxy".
    winw1: Set parameter "Start" for service "kube-proxy".
    winw1: Reset parameter "ObjectName" for service "kube-proxy" to its default.
    winw1: Set parameter "Type" for service "kube-proxy".
    winw1: Reset parameter "AppThrottle" for service "kube-proxy" to its default.
    winw1: Set parameter "AppStdout" for service "kube-proxy".
    winw1: 
    winw1: Set parameter "AppRotateFiles" for service "kube-proxy".
    winw1: Set parameter "AppRotateOnline" for service "kube-proxy".
    winw1: Set parameter "AppRotateSeconds" for service "kube-proxy".
    winw1: Set parameter "AppRotateBytes" for service "kube-proxy".
    winw1: Done installing kube-proxy service.
    winw1: Starting Kube-proxy and Kubelet...
 ~/projects/sig-windows-dev-tools   master  vagrant ssh controlplane
cni:
calico
Last login: Wed Sep 29 17:29:18 2021 from 10.0.2.2
vagrant@controlplane:~$ kubectl get nodes
NAME           STATUS     ROLES                  AGE     VERSION
controlplane   Ready      control-plane,master   3h13m   v1.21.0
winw1          NotReady   <none>                 129m    v1.21.2-rc.0
```
