### ISSUE TITLE
add tolerations to smoke test 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#79]
Pretty soon we'll be tainting our windows nodes, and along the way we'll want to also tolerate them accordingly

good first issue to add these tolerations into our smoke-test.yaml file 
```
 spec:
      tolerations:
       - effect: NoSchedule
          key: os
          operator: Equal
          value: windows
       - effect: NoSchedule
          key: os
          operator: Equal
          value: Windows
```

**Comment by jayunit100** [comment]
also add a nodeport service to it

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
```
